### PR TITLE
Merging kaunter-login into user-form-umum

### PR DESCRIPTION
**Pull request by nocturnalmc**
**INFO** untuk dato @c4lyp5o aku merge branch kaunter masuk branch umum

feat: removed kaunter/ubah route, removed kaunter edit page, added react toastify, created editable form, reworked graphql to fetch data on update

### CODE REVIEW

**Comment by nocturnalmc** [comment]
Aku merge tapi branch kaunter-login x delete lagi

**Comment by c4lyp5o** [comment]
Terbaik. Thanks dato.

**Comment by nocturnalmc** [comment]
Branch ni pun aku delete dato @c4lyp5o . Semua dah masuk branch main

**Comment by c4lyp5o** [comment]
Terbaik dato.

**Pull request merged**
