### PR TITLE
fix: hotfix 2

### PR DESCRIPTION
**Pull request by nocturnalmc**
[fix: encrypt ic only when kemaskini at umum](https://github.com/nocturnalmc/gp2/commit/e38941ddc9db507e2e169e666ce9df54e9a58700)
[catatan debug](https://github.com/nocturnalmc/gp2/commit/cc441583ab642adcaf9ea9576cad13942e7d99f3)
[fix: catatan map for Kemaskini](https://github.com/nocturnalmc/gp2/commit/b6ecfc9589af6164cd1a18af75436827d6ceb7ac) refer PR https://github.com/nocturnalmc/gp2/pull/333

[checking data, added alamat field for taska](https://github.com/nocturnalmc/gp2/commit/53131320f7121ede9b72c28c3c77fe530a2a011b) - @c4lyp5o Dato yang commit kau ni ada problem. Catatan taska kat model dah betul ubah tapi kau pass data dari properties kat Add.js dalam Ftype 'taska' || 'tadika' tu salah. Pastu edit jgk table header tu tukar kepada alamat eh dato

Aku buka pr masuk staging dlu sbb taska masih x pakai lagi kan. Nti @c4lyp5o dato fix eh

### CODE REVIEW

**Comment by c4lyp5o** [comment]
Dato @nocturnalmc , haha boleh x highlight kt mana yg salah tu..

**Comment by c4lyp5o** [comment]
> Dato @nocturnalmc , haha boleh x highlight kt mana yg salah tu.. 

Owh xpe aku faham dah haha..

**Comment by nocturnalmc** [comment]
> > Dato @nocturnalmc , haha boleh x highlight kt mana yg salah tu..
> 
> Owh xpe aku faham dah haha..

Orait dato. Sorry lupa pulak comment kat code tu

**Comment by nocturnalmc** [comment]
Dato @c4lyp5o tolong approve dlu boleh ke? Utk masuk staging. Ke dato rasa cmne

**Review by c4lyp5o — APPROVED** [review]
Onzz

**Pull request merged**
