### PR TITLE
C4lyp5o

### PR DESCRIPTION
**Pull request by c4lyp5o**
@nocturnalmc cuba test sikit dato tgk

### CODE REVIEW

**Review by nocturnalmc — COMMENTED** [review]
LGTM !

**Review by nocturnalmc — APPROVED** [review]
LGTM! Masuk dengan nama Allah bismillah @c4lyp5o

**Comment by c4lyp5o** [comment]
@nocturnalmc takbeeeerrrr Allahuakbar

**Comment by c4lyp5o** [comment]
@nocturnalmc dato jap, lgtm tu apa haha...

**Comment by nocturnalmc** [comment]
> @nocturnalmc dato jap, lgtm tu apa haha... 

Looks good to me !

Hahaa

**Comment by c4lyp5o** [comment]
Haha.. @nocturnalmc ingatkan seruan perang. Aku takbir la terus

**Comment by nocturnalmc** [comment]
Takpe takbir pun x salah. Allahuakbar ! @c4lyp5o nak gi perang 7hb ni hahaha

**Pull request merged**
