### PR TITLE
fix: excel baru pgs203

### PR DESCRIPTION
**Pull request by c4lyp5o**

### CODE REVIEW

**Comment by nocturnalmc** [comment]
Excel mapping dalam code sama ke dato? @c4lyp5o

**Comment by c4lyp5o** [comment]
@nocturnalmc aah excel sama. Matron mintak tukar formula dalam excel tu.

**Review by nocturnalmc — APPROVED** [review]
Orait dato bismillah @c4lyp5o

**Comment by c4lyp5o** [comment]
Alhamdulillah.... @nocturnalmc

**Pull request merged**
