### PR TITLE
Navbar tweaks for button reten

### PR DESCRIPTION
**Pull request by nocturnalmc**
1. Button will change to yellow color on hover or selected
2. Close the navbar when link is selected

### CODE REVIEW

**Comment by nocturnalmc** [comment]
Please review. Thank you !

**Comment by c4lyp5o** [comment]
hmm.. impressive. very nice.

**Review by c4lyp5o — APPROVED** [review]
yeehaw

**Comment by nocturnalmc** [comment]
Thank you dato ! :rocket:

**Pull request merged**
